### SignUp - Create new account

POST http://localhost:{{PORT}}/api/signup HTTP/1.1
Content-Type: application/json

{
  "name": "any_name",
  "email": "any_email@mail.com",
  "password": "any_password",
  "passwordConfirmation": "any_password"
}
